<?php

function rpgmain_menu () {
$items = array();

$items['admin/rpg/create/%/%'] = array(
  'title' => 'Create nodes',
  'page callback' => 'rpgmain_rpg_createnodes',
  'page arguments' => array(3, 4),
  'access arguments' => array('access content'),
  'type' => MENU_CALLBACK,
);

return $items;

}


function rpgmain_rpg_createnodes ($nodetype, $numnodes = 1) {
  dpm($nodetype);
  dpm($numnodes);

  $newnode = new stdClass();
  $newnode->type = $nodetype;
  $newnode->title = 'Choose a random name for me';
  $newnode->language = LANGUAGE_NONE;

  $newnode->field_distinguishing_features[$newnode->language][0]['value'] = 84;

  dpm($newnode, '$newnode before prepare');
  node_object_prepare($newnode);
  dpm($newnode, '$newnode after prepare');
  $node = node_submit($newnode);
  node_save($node);
  dpm($node, '$node after save');
  return 'bobo';
}

/**
* The main form_alter that will alter node forms in common ways
*/
function rpgmain_form_node_form_alter (&$form, &$form_state) {
  // Get all of the form elements to be randomized from the module that controls this content type.
  // After getting the elements to be randomized, pre-select all options for that element
  // Name the function _get_random_[node_type_machine_name]_fields.
  $type = $form['type']['#value'];
  $module = $type . 'rules';
  //dpm($module, '$module');
  $all_fields = field_info_fields($type); // Get all fields on this node type (random or not)
  // get them element types
  if (module_exists($module)) {
    $function = '_get_random_' . $type . '_fields';
    if (function_exists($function)) {
      $randomized_fields = $function();
      // Set them default values (all values are selected by default)
      foreach ($randomized_fields as $key => $field) {
        // Add the UX select all / deselect all options
        $form[$field]['und']['#title'] .= ' <span class="deselectall">(Deselect all</span>';
        $form[$field]['und']['#title'] .= ' <span class="selectall">Select all)</span>';
        
        $options = list_allowed_values($all_fields[$field]);
        $defaults = array();
        foreach ($options as $key => $option) {
          $defaults[] = $key;
        }
        $form[$field]['und']['#default_value'] = $defaults;

      }
    }
  }
}
